#!/bin/bash

################################################################################
#
# NOTE! This script suppresses the output generated by the 'diff' command. If
# you want to view the 'diff' results, you'll have to run that command directly.
#
#
# To run all test cases, copy this script to Eustis, place it in a directory
# with your Fibonacci.c file and all the test case files (source files and
# output files), and Fibonacci.h, and do the following:
#
# 1. Make this script executable by running the following command (you only
#    need to do this once, and then the file will remain executable):
#
#       chmod +x test-all.sh
#
# 2. Run this script like so:
#
#       ./test-all.sh
#
################################################################################


NUM_TEST_CASES=5

for i in `seq -f "%02g" 1 $NUM_TEST_CASES`;
do
	echo -n "Checking testcase$i... "

	# Attempt to compile.
	gcc Fibonacci.c testcase$i.c 2> /dev/null
	compile_val=$?
	if [[ $compile_val != 0 ]]; then
		echo "fail (failed to compile)"
		continue
	fi

	# Run program. Capture return value to check whether it crashes.
	./a.out > myoutput$i.txt 2> /dev/null
	execution_val=$?
	if [[ $execution_val != 0 ]]; then
		echo "fail (program crashed)"
		continue
	fi

	# Run diff and capture its return value.
	diff myoutput$i.txt output$i.txt > /dev/null
	diff_val=$?
	
	# Output results based on diff's return value.
	if  [[ $diff_val != 0 ]]; then
		echo "fail (output does not match)"
	else
		echo "PASS!"
	fi
done

# Clean up the executable file.
rm -f a.out

# Clean up the output files generated by this script.
for i in `seq -f "%02g" 1 $NUM_TEST_CASES`;
do
	rm -f myoutput$i.txt
done
